name: Update Goal Page

on:
  push:
    paths:
      - "goal.txt"

jobs:
  update-page:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Save files from main
        run: |
          mkdir temp
          cp goal.txt index.html temp/

      - name: Checkout or create gh-pages branch
        run: |
          git fetch origin
          if git show-ref --verify --quiet refs/heads/gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
            rm -rf *
          fi

      - name: Copy updated files to gh-pages
        run: |
          cp temp/goal.txt temp/index.html ./

      - name: Setup git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push
        run: |
          git add goal.txt index.html
          git commit -m "Update goal progress [auto]" || echo "No changes to commit"
          git push origin gh-pages
          
