name: Update Goal Page

on:
  push:
    paths:
      - "goal.txt"

jobs:
  update-page:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Prepare gh-pages branch
        run: |
          # ถ้ายังไม่มี gh-pages ให้สร้างใหม่จาก main
          if ! git show-ref --verify --quiet refs/heads/gh-pages; then
            git checkout -b gh-pages
          else
            git checkout gh-pages
            git merge origin/main --no-edit || true
          fi

      - name: Copy files
        run: |
          cp goal.txt index.html ./

      - name: Commit and push changes
        run: |
          git add goal.txt index.html
          git commit -m "Update goal progress [auto]" || echo "No changes to commit"
          git push origin gh-pages
          
